### ISSUE TITLE
Plugin complains that webtorrent-hybrid is missing...how do you install it?

### ISSUE THREAD

**Issue by salfter** [bitchute-kodi/plugin.video.bitchute#9]
I've gone through all of the default plugin repositories looking for this, but can't find it.  Searching the web turns up another project (https://github.com/webtorrent/webtorrent-hybrid), but this appears to require NodeJS, which isn't included in LibreELEC and also isn't available as a plugin (that I have been able to find).  Videos appear to play OK anyway (though the "Make sure that webtorrent-hybrid is installed..." nag is on-screen an inordinately long time), but it'd be nice to fix this if I could.

**Comment by jasonfrancis** [comment]
So [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid), which requires node.js, is necessary to be a good participant of the Bitchute community.

The brilliance of Bitchute is that when you're watching a video you're also sharing bits to other folks in the "swarm" watching that video.  Without webtorrent-hybrid you're always "leeching" from Bitchute's seed servers, racking up their bandwidth bill.

In a perfect world I'd like to implement webtorrent in python so you wouldn't need to install anything else, but I don't see myself getting the time to do that.

Feel free to make fork specifically for LibreELEC that suppresses that message.  Please update this ticket if you find a good method for shoehorning Node.js onto LibreELEC. I'm sure that'd help other folks.

**Comment by stuartraetaylor** [comment]
I was also wondering about this. Thanks for the explanation @jasonfrancis.

It sounds like in order the be a good citizen of Bitchute we would need to find out how to install webtorrent-hybrid and I'm assuming on LibreELEC that isn't trivial based on this thread.

Anyone who figures out how to install web-torrent hybrid instead of just disabling the message could reply here. I'll give it a try when I find the time. Then we can update the README file with instructions.
